#!/usr/bin/env python3
"""
ollama_mcp_server.py

A Model Context Protocol (MCP) server that bridges Ollama models into an IDE.
Implements 6 tools for health checking, listing, chatting, generating, showing, and pulling models.

Generated by: Qwen 3.5 397B (Ollama Cloud)
Audited by:   Qwen 3.5 397B (self-audit)
Hardened by:  Antigravity IDE agent (fixes #2,#3,#4,#5,#8,#9,#11)
"""

import os
import sys
import glob
import json
import asyncio
import logging

# ── VENV BOOTSTRAP ──────────────────────────────────────────────
# When executed by Glama's auto-generated Docker template, bare `python`
# resolves to the global interpreter while `uv sync` installs packages
# into /app/.venv. This bootstrap detects that situation and adds the
# venv site-packages to sys.path before any third-party imports.
_script_dir = os.path.dirname(os.path.abspath(__file__))
_venv_sp = glob.glob(os.path.join(_script_dir, ".venv", "lib", "python*", "site-packages"))
if _venv_sp and _venv_sp[0] not in sys.path:
    sys.path.insert(0, _venv_sp[0])

import httpx
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

# ── CONFIG ──────────────────────────────────────────────────────
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
REQUEST_TIMEOUT = float(os.getenv("OLLAMA_TIMEOUT", "300"))

# ── LOGGING (#8 fix) ───────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s: %(message)s")
log = logging.getLogger("ollama-mcp")

# ── HTTP CLIENT (#5 fix: singleton, #4 fix: no redirects) ─────
_client = httpx.AsyncClient(
    base_url=OLLAMA_HOST,
    timeout=httpx.Timeout(REQUEST_TIMEOUT, connect=10.0),
    follow_redirects=False,
)

# Initialize Server
app = Server("ollama")

# ── HELPERS ─────────────────────────────────────────────────────

def _build_options(arguments: dict) -> dict:
    """Extract Ollama options from MCP arguments. (#9 fix: DRY)"""
    options = {}
    if "temperature" in arguments:
        options["temperature"] = arguments["temperature"]
    max_tokens = arguments.get("max_tokens")
    if max_tokens is not None and max_tokens > 0:
        options["num_predict"] = max_tokens
    return options


def _safe_json(resp: httpx.Response) -> dict:
    """Parse JSON response safely. (#3 fix: handle non-JSON)"""
    try:
        return resp.json()
    except (json.JSONDecodeError, ValueError):
        return {"error": "Invalid JSON from Ollama", "raw": resp.text[:500]}


def _validate_required(arguments: dict, *keys: str) -> str | None:
    """Validate required arguments exist. (#2 fix: no KeyError)"""
    for key in keys:
        if key not in arguments or arguments[key] is None:
            return f"Missing required argument: '{key}'"
    return None


def _error(message: str, **extra) -> list[TextContent]:
    """Return a structured error response. (#11 fix: sanitized)"""
    payload = {"error": message}
    payload.update(extra)
    return [TextContent(type="text", text=json.dumps(payload, indent=2))]


def _ok(data: Any) -> list[TextContent]:
    """Return a structured success response."""
    return [TextContent(type="text", text=json.dumps(data, indent=2, default=str))]


# ── TOOL DEFINITIONS ───────────────────────────────────────────

TOOLS = [
    Tool(
        name="ollama_health",
        description=(
            "Check Ollama connectivity and list currently running models. "
            "This is a read-only diagnostic tool — use it first to verify the Ollama daemon is reachable "
            "before calling any other tool. No parameters required. "
            "Returns JSON with 'connected' (boolean), 'host' (the Ollama URL), and 'running_models' "
            "(array of currently loaded model objects). If the daemon is unreachable, returns a structured "
            "error with connection details instead of throwing."
        ),
        inputSchema={"type": "object", "properties": {}, "additionalProperties": False}
    ),
    Tool(
        name="ollama_list_models",
        description=(
            "List all available Ollama models and indicate which are currently loaded in memory. "
            "Read-only. Use this to discover which models are installed before calling ollama_chat "
            "or ollama_generate. Returns JSON with a 'models' array where each entry has 'name' (string), "
            "'size' (bytes as integer), 'modified_at' (ISO 8601 timestamp), and 'loaded' (boolean — true if "
            "the model is currently resident in GPU/CPU memory). No parameters required."
        ),
        inputSchema={"type": "object", "properties": {}, "additionalProperties": False}
    ),
    Tool(
        name="ollama_chat",
        description=(
            "Send a multi-turn chat completion request to an Ollama model and receive the full response. "
            "Use this for conversational interactions where message history matters. "
            "For single-prompt generation without history, use ollama_generate instead. "
            "The model must already be pulled (use ollama_list_models to check, ollama_pull_model to download). "
            "This tool makes a network request to the Ollama daemon and may take seconds to minutes "
            "depending on model size and prompt length. Not idempotent — each call generates a new response. "
            "Returns the full Ollama chat response JSON including 'message' (with 'role' and 'content'), "
            "'model', 'total_duration', 'eval_count', and token usage statistics."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": (
                        "The exact Ollama model identifier to use for inference. "
                        "Must match a name from ollama_list_models (e.g., 'llama3.1:8b', 'qwen2.5:7b', 'deepseek-r1:14b'). "
                        "Cloud models use the same format with a '-cloud' suffix (e.g., 'qwen3.5:397b-cloud')."
                    )
                },
                "messages": {
                    "type": "array",
                    "description": (
                        "Ordered list of chat messages forming the conversation history. "
                        "Each message must have 'role' ('user', 'assistant', or 'system') and 'content' (string). "
                        "Messages are sent in order — place system prompts first if not using the 'system' parameter."
                    ),
                    "items": {
                        "type": "object",
                        "properties": {
                            "role": {
                                "type": "string",
                                "enum": ["user", "assistant", "system"],
                                "description": "The role of the message author: 'user', 'assistant', or 'system'."
                            },
                            "content": {
                                "type": "string",
                                "description": "The text content of the message."
                            }
                        },
                        "required": ["role", "content"]
                    }
                },
                "temperature": {
                    "type": "number",
                    "description": (
                        "Sampling temperature controlling randomness. Range: 0.0 (deterministic) to 2.0 (very creative). "
                        "Default is model-dependent (typically 0.7–0.8). Lower values produce more focused, predictable output."
                    )
                },
                "max_tokens": {
                    "type": "integer",
                    "description": (
                        "Maximum number of tokens to generate in the response. Maps to Ollama's 'num_predict' parameter. "
                        "Set to -1 for unlimited generation. Default is model-dependent (typically 2048). "
                        "Must be a positive integer or -1."
                    )
                },
                "system": {
                    "type": "string",
                    "description": (
                        "System prompt prepended to the conversation. Sets the behavior, persona, or constraints for the model. "
                        "If provided, this is injected as the first message with role 'system' before the messages array."
                    )
                }
            },
            "required": ["model", "messages"],
            "additionalProperties": False
        }
    ),
    Tool(
        name="ollama_generate",
        description=(
            "Generate a single-turn text completion from an Ollama model without chat history. "
            "Use this for one-shot prompts, code generation, or text transformation tasks where "
            "conversation context is not needed. For multi-turn conversations, use ollama_chat instead. "
            "The model must already be pulled (use ollama_list_models to check availability). "
            "Makes a network request to the Ollama daemon — response time varies with model size and prompt length. "
            "Not idempotent — each call produces a new generation. "
            "Returns the full Ollama generate response JSON including 'response' (the generated text), "
            "'model', 'total_duration', 'eval_count', and performance metrics."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": (
                        "The exact Ollama model identifier (e.g., 'llama3.1:8b', 'codellama:13b'). "
                        "Must match a name from ollama_list_models."
                    )
                },
                "prompt": {
                    "type": "string",
                    "description": "The input text prompt to generate a completion from. Can be any length."
                },
                "temperature": {
                    "type": "number",
                    "description": (
                        "Sampling temperature (0.0–2.0). Lower values are more deterministic. "
                        "Default is model-dependent."
                    )
                },
                "max_tokens": {
                    "type": "integer",
                    "description": (
                        "Maximum tokens to generate. Maps to Ollama's 'num_predict'. "
                        "Set to -1 for unlimited. Must be a positive integer or -1."
                    )
                },
                "system": {
                    "type": "string",
                    "description": "System prompt to set model behavior and constraints for this generation."
                }
            },
            "required": ["model", "prompt"],
            "additionalProperties": False
        }
    ),
    Tool(
        name="ollama_show_model",
        description=(
            "Retrieve detailed metadata about a specific Ollama model. Read-only. "
            "Use this to inspect a model's license, parameter count, quantization, template format, "
            "and system prompt before using it with ollama_chat or ollama_generate. "
            "The model must be already pulled locally. "
            "Returns JSON with 'modelfile' (the Modelfile contents), 'parameters' (runtime defaults), "
            "'template' (the Go template for prompt formatting), and 'details' (family, parameter_size, "
            "quantization_level)."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": (
                        "The exact model identifier to inspect (e.g., 'llama3.1:8b'). "
                        "Must match a name from ollama_list_models."
                    )
                }
            },
            "required": ["model"],
            "additionalProperties": False
        }
    ),
    Tool(
        name="ollama_pull_model",
        description=(
            "Download a model from the Ollama library to the local machine. "
            "This is a WRITE operation with side effects — it downloads potentially large files (1–100+ GB) "
            "and stores them on disk. Execution time ranges from seconds to hours depending on model size "
            "and network speed. Use ollama_list_models first to check if the model is already available. "
            "The model name must be a valid Ollama library identifier. "
            "Returns JSON with download status. After pulling, the model becomes available for "
            "ollama_chat, ollama_generate, and ollama_show_model."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": (
                        "The model identifier to download from the Ollama library (e.g., 'llama3.1:8b', "
                        "'mistral:latest', 'codellama:13b-instruct'). Supports tag syntax for specific variants."
                    )
                }
            },
            "required": ["model"],
            "additionalProperties": False
        }
    )
]

# ── SERVER LOGIC ────────────────────────────────────────────────

@app.list_tools()
async def list_tools() -> list[Tool]:
    return TOOLS


@app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    """Dispatches tool calls to the appropriate Ollama API endpoint."""
    log.info(f"Tool call: {name} | model={arguments.get('model', 'n/a')}")

    try:
        # ── ollama_health ───────────────────────────────────
        if name == "ollama_health":
            root_resp = await _client.get("/")
            connected = root_resp.status_code == 200

            ps_data = {}
            try:
                ps_resp = await _client.get("/api/ps")
                ps_data = _safe_json(ps_resp)
            except Exception:
                pass

            return _ok({
                "connected": connected,
                "host": OLLAMA_HOST,
                "running_models": ps_data.get("models", [])
            })

        # ── ollama_list_models ──────────────────────────────
        elif name == "ollama_list_models":
            tags_resp = await _client.get("/api/tags")
            tags_data = _safe_json(tags_resp)

            ps_resp = await _client.get("/api/ps")
            ps_data = _safe_json(ps_resp)

            running_names = {m["name"] for m in ps_data.get("models", [])}

            models_list = []
            for model in tags_data.get("models", []):
                models_list.append({
                    "name": model.get("name", "unknown"),
                    "size": model.get("size"),
                    "modified_at": model.get("modified_at"),
                    "loaded": model.get("name", "") in running_names
                })

            return _ok({"models": models_list})

        # ── ollama_chat ─────────────────────────────────────
        elif name == "ollama_chat":
            err = _validate_required(arguments, "model", "messages")
            if err:
                return _error(err)

            payload = {
                "model": arguments["model"],
                "messages": arguments["messages"],
                "stream": False
            }
            if "system" in arguments:
                payload["messages"] = [
                    {"role": "system", "content": arguments["system"]}
                ] + payload["messages"]

            options = _build_options(arguments)
            if options:
                payload["options"] = options

            resp = await _client.post("/api/chat", json=payload)
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_generate ─────────────────────────────────
        elif name == "ollama_generate":
            err = _validate_required(arguments, "model", "prompt")
            if err:
                return _error(err)

            payload = {
                "model": arguments["model"],
                "prompt": arguments["prompt"],
                "stream": False
            }
            if "system" in arguments:
                payload["system"] = arguments["system"]

            options = _build_options(arguments)
            if options:
                payload["options"] = options

            resp = await _client.post("/api/generate", json=payload)
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_show_model ───────────────────────────────
        elif name == "ollama_show_model":
            err = _validate_required(arguments, "model")
            if err:
                return _error(err)

            resp = await _client.post("/api/show", json={"name": arguments["model"]})
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_pull_model ───────────────────────────────
        elif name == "ollama_pull_model":
            err = _validate_required(arguments, "model")
            if err:
                return _error(err)

            log.info(f"Pulling model: {arguments['model']}")
            resp = await _client.post("/api/pull", json={"name": arguments["model"], "stream": False})
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── unknown tool ────────────────────────────────────
        else:
            return _error(f"Unknown tool: {name}")

    except httpx.ConnectError:
        log.error(f"Connection failed to {OLLAMA_HOST}")
        return _error("Connection Failed", details=f"Could not connect to Ollama at {OLLAMA_HOST}. Is it running?")
    except httpx.TimeoutException:
        log.error(f"Request timed out after {REQUEST_TIMEOUT}s")
        return _error("Timeout", details=f"Request timed out after {REQUEST_TIMEOUT}s. Increase OLLAMA_TIMEOUT env var for cloud models.")
    except httpx.HTTPStatusError as e:
        log.error(f"HTTP {e.response.status_code}: {e.response.text[:200]}")
        return _error("HTTP Error", status_code=e.response.status_code, details=e.response.text[:500])
    except Exception as e:
        log.exception("Unexpected error in tool call")
        return _error("Internal server error")

# ── MAIN ────────────────────────────────────────────────────────

SERVER_INSTRUCTIONS = (
    "Ollama-Omega bridges any Ollama model — local or cloud — into your IDE via MCP. "
    "Recommended workflow: (1) Call ollama_health to verify connection. "
    "(2) Call ollama_list_models to discover available models. "
    "(3) If the needed model is not listed, call ollama_pull_model to download it. "
    "(4) Use ollama_chat for multi-turn conversations or ollama_generate for single-prompt completions. "
    "(5) Use ollama_show_model to inspect model metadata, license, and quantization details. "
    "All tools return structured JSON. Error responses always include an 'error' key with a human-readable message. "
    "The server connects to the Ollama daemon at OLLAMA_HOST (default: http://localhost:11434). "
    "Cloud-hosted models accessible through the same tools if the Ollama daemon supports them."
)


async def main():
    log.info(f"Ollama MCP Server starting | host={OLLAMA_HOST} timeout={REQUEST_TIMEOUT}s")
    async with stdio_server() as (read, write):
        init_options = app.create_initialization_options()
        init_options.instructions = SERVER_INSTRUCTIONS
        await app.run(read, write, init_options)


if __name__ == "__main__":
    asyncio.run(main())
