#!/usr/bin/env python3
"""
ollama_mcp_server.py

A Model Context Protocol (MCP) server that bridges Ollama models into an IDE.
Implements 6 tools for health checking, listing, chatting, generating, showing, and pulling models.

Generated by: Qwen 3.5 397B (Ollama Cloud)
Audited by:   Qwen 3.5 397B (self-audit)
Hardened by:  Antigravity IDE agent (fixes #2,#3,#4,#5,#8,#9,#11)
"""

import os
import sys
import glob
import json
import asyncio
import logging

# ── VENV BOOTSTRAP ──────────────────────────────────────────────
# When executed by Glama's auto-generated Docker template, bare `python`
# resolves to the global interpreter while `uv sync` installs packages
# into /app/.venv. This bootstrap detects that situation and adds the
# venv site-packages to sys.path before any third-party imports.
_script_dir = os.path.dirname(os.path.abspath(__file__))
_venv_sp = glob.glob(os.path.join(_script_dir, ".venv", "lib", "python*", "site-packages"))
if _venv_sp and _venv_sp[0] not in sys.path:
    sys.path.insert(0, _venv_sp[0])

import httpx
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

# ── CONFIG ──────────────────────────────────────────────────────
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
REQUEST_TIMEOUT = float(os.getenv("OLLAMA_TIMEOUT", "300"))

# ── LOGGING (#8 fix) ───────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s: %(message)s")
log = logging.getLogger("ollama-mcp")

# ── HTTP CLIENT (#5 fix: singleton, #4 fix: no redirects) ─────
_client = httpx.AsyncClient(
    base_url=OLLAMA_HOST,
    timeout=httpx.Timeout(REQUEST_TIMEOUT, connect=10.0),
    follow_redirects=False,
)

# Initialize Server
app = Server("ollama")

# ── HELPERS ─────────────────────────────────────────────────────

def _build_options(arguments: dict) -> dict:
    """Extract Ollama options from MCP arguments. (#9 fix: DRY)"""
    options = {}
    if "temperature" in arguments:
        options["temperature"] = arguments["temperature"]
    max_tokens = arguments.get("max_tokens")
    if max_tokens is not None and max_tokens > 0:
        options["num_predict"] = max_tokens
    return options


def _safe_json(resp: httpx.Response) -> dict:
    """Parse JSON response safely. (#3 fix: handle non-JSON)"""
    try:
        return resp.json()
    except (json.JSONDecodeError, ValueError):
        return {"error": "Invalid JSON from Ollama", "raw": resp.text[:500]}


def _validate_required(arguments: dict, *keys: str) -> str | None:
    """Validate required arguments exist. (#2 fix: no KeyError)"""
    for key in keys:
        if key not in arguments or arguments[key] is None:
            return f"Missing required argument: '{key}'"
    return None


def _error(message: str, **extra) -> list[TextContent]:
    """Return a structured error response. (#11 fix: sanitized)"""
    payload = {"error": message}
    payload.update(extra)
    return [TextContent(type="text", text=json.dumps(payload, indent=2))]


def _ok(data: Any) -> list[TextContent]:
    """Return a structured success response."""
    return [TextContent(type="text", text=json.dumps(data, indent=2, default=str))]


# ── TOOL DEFINITIONS ───────────────────────────────────────────

TOOLS = [
    Tool(
        name="ollama_health",
        description="Check Ollama connectivity and list currently running models.",
        inputSchema={"type": "object", "properties": {}}
    ),
    Tool(
        name="ollama_list_models",
        description="List all available Ollama models and indicate which are currently loaded in memory.",
        inputSchema={"type": "object", "properties": {}}
    ),
    Tool(
        name="ollama_chat",
        description="Send a chat completion request to an Ollama model. Returns the full response.",
        inputSchema={
            "type": "object",
            "properties": {
                "model": {"type": "string", "description": "Model name (e.g., 'llama3')"},
                "messages": {
                    "type": "array",
                    "description": "List of message objects with 'role' and 'content'",
                    "items": {
                        "type": "object",
                        "properties": {
                            "role": {"type": "string"},
                            "content": {"type": "string"}
                        },
                        "required": ["role", "content"]
                    }
                },
                "temperature": {"type": "number", "description": "Sampling temperature"},
                "max_tokens": {"type": "integer", "description": "Max tokens to generate (maps to num_predict)"},
                "system": {"type": "string", "description": "System prompt"}
            },
            "required": ["model", "messages"]
        }
    ),
    Tool(
        name="ollama_generate",
        description="Generate a response for a given prompt without chat history.",
        inputSchema={
            "type": "object",
            "properties": {
                "model": {"type": "string", "description": "Model name"},
                "prompt": {"type": "string", "description": "The prompt to generate from"},
                "temperature": {"type": "number", "description": "Sampling temperature"},
                "max_tokens": {"type": "integer", "description": "Max tokens to generate"},
                "system": {"type": "string", "description": "System prompt"}
            },
            "required": ["model", "prompt"]
        }
    ),
    Tool(
        name="ollama_show_model",
        description="Show detailed information about a specific model (license, parameters, etc.).",
        inputSchema={
            "type": "object",
            "properties": {
                "model": {"type": "string", "description": "Model name"}
            },
            "required": ["model"]
        }
    ),
    Tool(
        name="ollama_pull_model",
        description="Download a model from the Ollama library. This may take a while.",
        inputSchema={
            "type": "object",
            "properties": {
                "model": {"type": "string", "description": "Model name to pull"}
            },
            "required": ["model"]
        }
    )
]

# ── SERVER LOGIC ────────────────────────────────────────────────

@app.list_tools()
async def list_tools() -> list[Tool]:
    return TOOLS


@app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    """Dispatches tool calls to the appropriate Ollama API endpoint."""
    log.info(f"Tool call: {name} | model={arguments.get('model', 'n/a')}")

    try:
        # ── ollama_health ───────────────────────────────────
        if name == "ollama_health":
            root_resp = await _client.get("/")
            connected = root_resp.status_code == 200

            ps_data = {}
            try:
                ps_resp = await _client.get("/api/ps")
                ps_data = _safe_json(ps_resp)
            except Exception:
                pass

            return _ok({
                "connected": connected,
                "host": OLLAMA_HOST,
                "running_models": ps_data.get("models", [])
            })

        # ── ollama_list_models ──────────────────────────────
        elif name == "ollama_list_models":
            tags_resp = await _client.get("/api/tags")
            tags_data = _safe_json(tags_resp)

            ps_resp = await _client.get("/api/ps")
            ps_data = _safe_json(ps_resp)

            running_names = {m["name"] for m in ps_data.get("models", [])}

            models_list = []
            for model in tags_data.get("models", []):
                models_list.append({
                    "name": model.get("name", "unknown"),
                    "size": model.get("size"),
                    "modified_at": model.get("modified_at"),
                    "loaded": model.get("name", "") in running_names
                })

            return _ok({"models": models_list})

        # ── ollama_chat ─────────────────────────────────────
        elif name == "ollama_chat":
            err = _validate_required(arguments, "model", "messages")
            if err:
                return _error(err)

            payload = {
                "model": arguments["model"],
                "messages": arguments["messages"],
                "stream": False
            }
            if "system" in arguments:
                payload["messages"] = [
                    {"role": "system", "content": arguments["system"]}
                ] + payload["messages"]

            options = _build_options(arguments)
            if options:
                payload["options"] = options

            resp = await _client.post("/api/chat", json=payload)
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_generate ─────────────────────────────────
        elif name == "ollama_generate":
            err = _validate_required(arguments, "model", "prompt")
            if err:
                return _error(err)

            payload = {
                "model": arguments["model"],
                "prompt": arguments["prompt"],
                "stream": False
            }
            if "system" in arguments:
                payload["system"] = arguments["system"]

            options = _build_options(arguments)
            if options:
                payload["options"] = options

            resp = await _client.post("/api/generate", json=payload)
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_show_model ───────────────────────────────
        elif name == "ollama_show_model":
            err = _validate_required(arguments, "model")
            if err:
                return _error(err)

            resp = await _client.post("/api/show", json={"name": arguments["model"]})
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── ollama_pull_model ───────────────────────────────
        elif name == "ollama_pull_model":
            err = _validate_required(arguments, "model")
            if err:
                return _error(err)

            log.info(f"Pulling model: {arguments['model']}")
            resp = await _client.post("/api/pull", json={"name": arguments["model"], "stream": False})
            resp.raise_for_status()
            return _ok(_safe_json(resp))

        # ── unknown tool ────────────────────────────────────
        else:
            return _error(f"Unknown tool: {name}")

    except httpx.ConnectError:
        log.error(f"Connection failed to {OLLAMA_HOST}")
        return _error("Connection Failed", details=f"Could not connect to Ollama at {OLLAMA_HOST}. Is it running?")
    except httpx.TimeoutException:
        log.error(f"Request timed out after {REQUEST_TIMEOUT}s")
        return _error("Timeout", details=f"Request timed out after {REQUEST_TIMEOUT}s. Increase OLLAMA_TIMEOUT env var for cloud models.")
    except httpx.HTTPStatusError as e:
        log.error(f"HTTP {e.response.status_code}: {e.response.text[:200]}")
        return _error("HTTP Error", status_code=e.response.status_code, details=e.response.text[:500])
    except Exception as e:
        log.exception("Unexpected error in tool call")
        return _error("Internal server error")

# ── MAIN ────────────────────────────────────────────────────────

async def main():
    log.info(f"Ollama MCP Server starting | host={OLLAMA_HOST} timeout={REQUEST_TIMEOUT}s")
    async with stdio_server() as (read, write):
        await app.run(read, write, app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
